# Generated by Django 4.2.2 on 2023-06-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Team',
        ),
    ]
